// This file is generated by Freight Price Movement Agent

// Importing the LoginPage component from its module
import LoginPage from './LoginPage';
// Importing the DashboardPage component from its module
import DashboardPage from './DashboardPage';
// Importing the NotFoundPage component from its module
import NotFoundPage from './NotFoundPage';
// Importing the DataSourcesPage component from its module
import DataSourcesPage from './DataSourcesPage';
// Importing the AddDataSourcePage component from its module
import AddDataSourcePage from './AddDataSourcePage';
// Importing the EditDataSourcePage component from its module
import EditDataSourcePage from './EditDataSourcePage';
// Importing the AnalysisPage component from its module
import AnalysisPage from './AnalysisPage';
// Importing the NewAnalysisPage component from its module
import NewAnalysisPage from './NewAnalysisPage';
// Importing the AnalysisResultsPage component from its module
import AnalysisResultsPage from './AnalysisResultsPage';
// Importing the ReportsPage component from its module
import ReportsPage from './ReportsPage';
// Importing the CreateReportPage component from its module
import CreateReportPage from './CreateReportPage';
// Importing the ReportDetailsPage component from its module
import ReportDetailsPage from './ReportDetailsPage';
// Importing the SettingsPage component from its module
import SettingsPage from './SettingsPage';

// Exporting the LoginPage component for use in routing and navigation
export { LoginPage };
// Exporting the DashboardPage component for use in routing and navigation
export { DashboardPage };
// Exporting the NotFoundPage component for use in routing and navigation
export { NotFoundPage };
// Exporting the DataSourcesPage component for use in routing and navigation
export { DataSourcesPage };
// Exporting the AddDataSourcePage component for use in routing and navigation
export { AddDataSourcePage };
// Exporting the EditDataSourcePage component for use in routing and navigation
export { EditDataSourcePage };
// Exporting the AnalysisPage component for use in routing and navigation
export { AnalysisPage };
// Exporting the NewAnalysisPage component for use in routing and navigation
export { NewAnalysisPage };
// Exporting the AnalysisResultsPage component for use in routing and navigation
export { AnalysisResultsPage };
// Exporting the ReportsPage component for use in routing and navigation
export { ReportsPage };
// Exporting the CreateReportPage component for use in routing and navigation
export { CreateReportPage };
// Exporting the ReportDetailsPage component for use in routing and navigation
export { ReportDetailsPage };
// Exporting the SettingsPage component for use in routing and navigation
export { SettingsPage };