---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: freight-price-agent
  labels:
    app: freight-price-movement-agent
    component: secrets
    tier: application
type: Opaque
data:
  DATABASE_URL: ${BASE64_DATABASE_URL}
  REDIS_URL: ${BASE64_REDIS_URL}
  SECRET_KEY: ${BASE64_SECRET_KEY}
  JWT_SECRET_KEY: ${BASE64_JWT_SECRET_KEY}
  CURRENCY_API_KEY: ${BASE64_CURRENCY_API_KEY}
  AWS_ACCESS_KEY_ID: ${BASE64_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_AWS_SECRET_ACCESS_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
  namespace: freight-price-agent
  labels:
    app: freight-price-movement-agent
    component: secrets
    tier: frontend
type: Opaque
data:
  AUTH_SECRET_KEY: ${BASE64_AUTH_SECRET_KEY}
  ANALYTICS_API_KEY: ${BASE64_ANALYTICS_API_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: freight-price-agent
  labels:
    app: freight-price-movement-agent
    component: secrets
    tier: data
type: Opaque
data:
  POSTGRES_USER: ${BASE64_POSTGRES_USER}
  POSTGRES_PASSWORD: ${BASE64_POSTGRES_PASSWORD}
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}